{
  imports = [
    ./options.nix
    ./common.nix
    ./mounts.nix
    ./services/affine.nix
    ./services/fizzy.nix
    ./services/firefly.nix
    ./services/gitea.nix
    ./services/homebox.nix
    ./services/invoiceplane.nix
    ./services/kaneo.nix
    ./services/keeper.nix
    ./services/listmonk.nix
    ./services/metube.nix
    ./services/outline.nix
    ./services/plane.nix
    ./services/postiz.nix
    ./services/stirling-pdf.nix
    ./services/sure.nix
    ./backup.nix
    ./firewall.nix
    ./recovery-notes.nix
  ];
}
